create table habit (id int8 generated by default as identity, frequency int8, created_at timestamp, description varchar(255), edited_at timestamp, title varchar(255), primary key (id));
create table journal_entry (id int8 generated by default as identity, created_at timestamp, description varchar(255), edited_at timestamp, habit_id int8, primary key (id));
create table users (id int8 generated by default as identity, created_at timestamp, edited_at timestamp, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists journal_entry add constraint FK3045ke4o4mm4fmj9151ltyu0 foreign key (habit_id) references habit;
