create table habit (id int8 generated by default as identity, completed boolean not null, description varchar(255), title varchar(255), primary key (id));
create table journal_entry (id int8 generated by default as identity, created_at timestamp, description varchar(255), edited_at timestamp, belongs_to_id int8, primary key (id));
alter table if exists journal_entry add constraint FK7rt6ab3isf1dw3igdsp4mvqu6 foreign key (belongs_to_id) references habit;
